### ISSUE TITLE
Use ember-power-select

### ISSUE THREAD

**Issue by ghost** [poteto/ember-hypersearch#12]
It will make your life way more easier if you do.

http://www.ember-power-select.com/docs/asynchronous-search

**Comment by poteto** [comment]
What does this issue mean? Stop working on this addon and use power-select?

**Comment by ghost** [comment]
No, use the UX experience from power-select and layer on the hypersearch sauce!

I maintained a custom thing like this, but the time invested in keeping the UX (opening, selecting, showing labels, etc) of the select part was a huge drag, we recently switched that to using power-select, it hugely improved my life quality.

(I'm sorry the initial issue was a bit aggressive in wording.)

**Comment by poteto** [comment]
Right, but this addon isn't meant to be only used as a dropdown, it is just a fast searchbox with internal cache and soon-to-be-implemented fuzzy search && is UI agnostic. The consuming application can use the results in whatever manner they like.

The current component template is probably a little misleading, I intend to eventually just turn this into a `tagName: 'input'`  component without the results being rendered in a list

**Comment by ghost** [comment]
Ah ok, got it, the `README.md` made it look like it was going that way.

**Comment by poteto** [comment]
Haha np, I appreciate the suggestion :) This addon is effectively still WIP, and I should update the README with my plans for it

**Comment by ghost** [comment]
I might be able to contribute some of the stuff we did in the project im working on.

**Comment by poteto** [comment]
Thanks, that would be great! I'm basing this addon on the React one I built in my old job – http://www.homely.com.au/

Features I plan to build:
- Option to persist cache to IndexedDB/WebSQL/localStorage/whatever
- Fuzzy search in cache
- Caches selected results 
- Option to restore last selected result on initial render
- API to remove a single or all cached selected results
- Cache invalidation after a set amount of time/days

**Comment by ghost** [comment]
Is it supposed to just load a 'dumb' JSON data structure? Or would searching within an ember data endpoint be inside the scope of things this addon would do?

**Comment by poteto** [comment]
For now yeah, but I don't see why the addon couldn't have the search handled by `store.query` in the route, and then have the results sent back in and cached
