### ISSUE TITLE
No updates in months... forking

### ISSUE THREAD

**Issue by Artistan** [poteto/ember-hypersearch#23]
Just an FYI to others looking to use this package.
I have forked it and integrated all the pull requests manually.

https://github.com/Artistan/ember-hypersearcher
https://www.npmjs.com/package/ember-hypersearcher
https://travis-ci.org/Artistan/ember-hypersearcher

this includes some bug fixes and other features such as the debounceAfter and Arrow Selection pull requests that I needed.

Cheers!

**Comment by jcowley** [comment]
You didn't even credit the original author. You just lifted the project and published it on npm under your name. 

Seems really lame IMHO.

**Comment by Artistan** [comment]
Forked, Fixed, Published.
I needed it to work, not wait another 6 months for an update.
Also merged in all the active pull requests at the time.
Cheers.
